// code-coverage-angular/src/app/number-checker.component.ts
import {Component, Input} from '@angular/core';

@Component({
  selector: 'number-checker',
  template: `
    <div>
      <button (click)="handleClick()">Click me</button>
      <span id="counter">{{count}}</span>
      <br/>
      <span id="result">{{result}}</span>
    </div>
  `,
})
class NumberCheckerComponent {
  @Input() array: number[] = [];
  @Input() number: number = 0;
  count = 0;
  result = 'No result yet';

  handleClick() {
    this.count++;
    if (this.array.includes(this.number)) {
      this.result = 'Array contains number';
    } else {
      this.result = 'Array doesn\'t contain number';
    }
  }
}

export {NumberCheckerComponent};

// code-coverage-vue/src/components/NumberChecker.vue
<script setup lang="ts">
import {ref} from "vue";

const props = defineProps<{
  array: number[],
  number: number
}>()

const count = ref(0);
const result = ref('No result yet');

function handeClick() {
  count.value++;
  if (props.array.includes(props.number)) {
    result.value = 'Array contains number';
  } else {
    result.value = 'Array doesn\'t contain number';
  }
}
</script>

<template>
  <div>
    <button data-testid="clickme-button" @click="handeClick">Click me</button>
    <span id="counter">{{ count }}</span>
    <br/>
    <span id="result">{{ result }}</span>
  </div>
</template>
