// code-coverage-react/src/NumberChecker.tsx
import * as React from 'react';

interface Props {
    array: number[];
    number: number
}

export const NumberChecker: React.FC<Props> = ({array, number}) => {
    const [count, setCount] = React.useState(0);
    const [result, setResult] = React.useState('No result yet');

    function handleClick(e: React.MouseEvent<HTMLButtonElement>) {
        setCount(count + 1);
        if (array.includes(number)) {
            setResult('Array contains number');
        } else {
            setResult('Array doesn\'t contain number');
        }
    }

    return (
        <div>
            <button data-testid="clickme-button" onClick={e => handleClick(e)}>Click me</button>
            <span data-testid="counter">{count}</span>
            <br/>
            <span data-testid="result">{result}</span>
        </div>
    );
};

// code-coverage-vue/src/components/NumberChecker.vue
<script setup lang="ts">
import {ref} from "vue";

const props = defineProps<{
  array: number[],
  number: number
}>()

const count = ref(0);
const result = ref('No result yet');

function handeClick() {
  count.value++;
  if (props.array.includes(props.number)) {
    result.value = 'Array contains number';
  } else {
    result.value = 'Array doesn\'t contain number';
  }
}
</script>

<template>
  <div>
    <button data-testid="clickme-button" @click="handeClick">Click me</button>
    <span id="counter">{{ count }}</span>
    <br/>
    <span id="result">{{ result }}</span>
  </div>
</template>
